### PR TITLE
Make Rainlab Translatable Implementation Really Optional

### PR DESCRIPTION
**Pull request by roseffendi**
Fixes # .

This pull request suppress error for translatable implementation.

Changes proposed in this pull request:

* Make Rainlab Translatable plugin optional

@GinoPane

### CODE REVIEW

**Comment by GinoPane** [comment]
Hi!
Did you have issues with that? Maybe any errors or exceptions?
Seems strange because I tested it without Translatable plugin installed and got no problems.

**Comment by GinoPane** [comment]
Huh, interesting, it really fails 🤷‍♂️ 
Thanks! I'll merge it soon.

**Comment by exaline-ru** [comment]
Hello! My Blog Taxonomy plugin does not want to add a tag and a series in Russian (as the main language of the site). Can this be eliminated or not? (the Translate plugin is also installed, but it doesn't help).

**Comment by roseffendi** [comment]
> Huh, interesting, it really fails 
> Thanks! I'll merge it soon.

Sure, you are welcome.

**Comment by GinoPane** [comment]
@exaline-ru Hi!
Could you please create an issue in "Issues" tab so we can discuss it there? This thread is for unrelated pull request 😄

**Comment by exaline-ru** [comment]
Yes. Added a topic there.

**Pull request merged**
